### ISSUE TITLE
Get "https://duo.com/": x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by seanbrhn3** [duosecurity/duo_api_golang#31]
Since the SDK doesn't have the capability to run CRUD operations on admins I was trying to make my own. heres my code
```	url := " /admin/v1/admins"
       d := duoapi.NewDuoApi(configInfo[0], configInfo[1], configInfo[2], "")
	params, _ := query.Values(admin)
	resp, _, err := d.SignedCall("GET", url, params)
	if err != nil {
		log.Fatal(err)
	}
```
It seems like the cert you have pinned when creating a newDuoApi isn't trusted

**Comment by xdesai** [comment]
Hey Sean! 
We chatted about this internally and we think the reason you're seeing this might be because your API host is not correct.
In the error snippet you posted I see that a GET request was issued to https://duo.com
duo.com is where we host our documentation, marketing information, etc. but the service that responds to API requests uses a different host. That host value will be specific to you and you would get it from the Duo Admin Panel in your admin api integration.

Another piece of evidence that points us away from the pinned certs being the issue is that we checked that the certs we have pinned in this repo match the certs that we use in our other sdks/language clients so I'm hesitant to say that it's the incorrect cert.
